# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-EscapeEvil-AllowAll
version:      0.04
version_from: AllowAll.pm
installdirs:  site
requires:
    File::Basename:                2.73
    File::Spec:                    3.01
    HTML::EscapeEvil:              0.04
    YAML:                          0.58

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
